### ISSUE TITLE
La exportul din tabelul clienti in documentul excel apare un camp in plus

### ISSUE THREAD

**Issue by LoredanaChitaru** [SoftulmeuRo/traduceri#1]
Pasul 1.
-  Am intrat in ecranul "Proiecte -> Clienti".
![traduceri clienti 1](https://cloud.githubusercontent.com/assets/12709407/7957898/60d72488-09f3-11e5-81dd-776ae68c26b3.jpg)

Pasul 2
 - Am apasat pe butonul "Export" si am descarcat documentul Excel.

Pasul 3:
 -  Am deschis documentul si am observat ca in document exista un camp completat cu: "{IDCompanii}"

![traduceri excel](https://cloud.githubusercontent.com/assets/12709407/7957958/c7df43d6-09f3-11e5-9ee6-fce883e84c54.jpg)

**Comment by crystyn90** [comment]
Rezolvat,
