### ISSUE TITLE
Nu se recunoaste traducatorul introdus in gridul "Cotatie furnizor pe task"

### ISSUE THREAD

**Issue by andreicorbu** [SoftulmeuRo/traduceri#10]
Pasul 1)
- Am intrat in fereastra "Proiecte -> Proiecte"
- Am creat un proiect simplu prin comanda "Adauga proiect simplu":

![tr9](https://cloud.githubusercontent.com/assets/12709454/7960470/7e530caa-0a09-11e5-9427-4c6e545ab1fe.PNG)

Pasul 2) 
- In proiectul nou creat am completat formularul "Cotatii furnizori pe task"
- Am incercat sa salvez cu butonul "Salveaza" de la commander:

![tr14](https://cloud.githubusercontent.com/assets/12709454/7960669/e6ca2394-0a0a-11e5-8b9f-53fca7da8ed3.PNG)

Pasul 3)
- Am salvat din butonul "Salveaza" din lista de commanderi.
- Am incercat sa mai salvez inca o data din butonul "Salveaza" din lisat de commaderi si am constata ca mi-a aparut urmatoarea eroare:

"   Cotatii furnizori pe task: container check 'save' error
        Traducatorul este obligatoriu!   "

- Se poate observa ca "Traducatorul" este selectat in formularul "Cotatii furnizori pe task"

![tr10](https://cloud.githubusercontent.com/assets/12709454/7960895/81857d4c-0a0c-11e5-899b-81e14e7de17f.PNG)

**Comment by t1b1c** [comment]
Am scos butonul salveaza din Commanders, este posibil ca el sa fi provocat pierderea randului current.
Mai incearca o data doar cu Salveaza de pe randul respectiv

**Comment by andreicorbu** [comment]
- Butonul "Salveaza" prezent pe rand nu salveaza randul introdus. Acest buton are functia de Editare pe un camp introdus deja in grid.
- Butonul care salva un rand nou introdus era butonul "Salveaza" din Commanders. 
- Acum nu se mai pot salva randurile noi pe care vrem sa le introducem.
