### ISSUE TITLE
Butonul "Excel" din gridul "Cotatie furnizor pe task" nu functioneaza

### ISSUE THREAD

**Issue by andreicorbu** [SoftulmeuRo/traduceri#11]
Pasul 1)
- Am intrat in fereastra "Proiecte -> Proiecte"
- Am creat un proiect simplu prin comanda "Adauga proiect simplu":

![tr9](https://cloud.githubusercontent.com/assets/12709454/7960470/7e530caa-0a09-11e5-9427-4c6e545ab1fe.PNG)

Pasul 2) 
- In proiectul nou creat am completat formularul "Cotatii furnizori pe task"

![tr14](https://cloud.githubusercontent.com/assets/12709454/7960669/e6ca2394-0a0a-11e5-8b9f-53fca7da8ed3.PNG)

Pasul 3)
- Am incercat sa efectuez un export in excel din butonul " excel" insa nu s-a intamplat nimic.
- Se pare ca butonul nu este functional.

![tr15](https://cloud.githubusercontent.com/assets/12709454/7960813/f3fc90d2-0a0b-11e5-8fb7-d3ec9b03f122.PNG)

**Comment by LoredanaChitaru** [comment]
test

**Comment by andreicorbu** [comment]
test2
