### ISSUE TITLE
Pot introduce orice fel de intrari la "Data primire", "Dat in lucru", "Termen intern", "Termen client"

### ISSUE THREAD

**Issue by andreicorbu** [SoftulmeuRo/traduceri#12]
Pasul 1)
- Am intrat in ecranul "Proiecte -> Proiecte"  si am introdus un nou proiect:

![tr8](https://cloud.githubusercontent.com/assets/12709454/7980950/5436c820-0ab4-11e5-871a-de67602af272.PNG)

Pasul 2) 
- Cand am completat formularul de detalii la "Data primire" am trecut 04.06.2015
- Cand am completat "Dat in lucru" am trecut o data gresita ( 01.06.2015 ) inainte ca documentul sa intre in firma.
- Am trecut date gresite si la "Termen intern" si "Terment client"
- Am salvat din butonul "Salveaza" fara nici o atentionare 
 
![tr7](https://cloud.githubusercontent.com/assets/12709454/7981011/bc21fb44-0ab4-11e5-8e7c-488a7de5a2a9.PNG)

**Comment by t1b1c** [comment]
Nu e o problema pt ei, nu s-au incurcat pana acum
