### ISSUE TITLE
Butonul "Salveaza" are functiile butonului "Activ"

### ISSUE THREAD

**Issue by andreicorbu** [SoftulmeuRo/traduceri#15]
Pasul 1)
- Am intrat in fereastra "Proiecte -> Proiecte" si am introdus un proiect simplu:

![c4](https://cloud.githubusercontent.com/assets/12709454/7982195/bedab606-0abd-11e5-9702-c9b84f6a44a5.PNG)

Pasul 2) 
- Am introdus o intrare in gridul "Cotatii furnizori pe task " si am incercat sa salvez din butonul "Salveaza".
- An apasat butonul "Afiseaza" pentru a vizualiza toate intrarile din grid:

![c1](https://cloud.githubusercontent.com/assets/12709454/7982244/2b38a722-0abe-11e5-800b-022fdb3e340f.PNG)

Pasul 3)
- Am observat ca randul nou introdus nu s-a salvat.
- Am incercat sa dau "Salveaza" pe un camp deja existent in grid-ul respectiv:

![c2](https://cloud.githubusercontent.com/assets/12709454/7982262/5aaa5d0c-0abe-11e5-915a-94fdd5e4e503.PNG)

Pasul 4)
- Am observat ca campul respectiv a devenit editabil:

![c3](https://cloud.githubusercontent.com/assets/12709454/7982269/6aea2f44-0abe-11e5-9096-719b0d9edb32.PNG)

Concluzie:
- Butonul "Salveaza" are functiile butonului "Activ"

**Comment by t1b1c** [comment]
asa trebuie sa functioneze
