### ISSUE TITLE
Nu se salveaza corect datele din grid-ul "Cotatii furnizori pe proiect"

### ISSUE THREAD

**Issue by andreicorbu** [SoftulmeuRo/traduceri#17]
Pasul 1)
- Am intrat in fereastra "Proiecte -> Proiecte"
- Am adaugat un proiect simplu:

![t2](https://cloud.githubusercontent.com/assets/12709454/8006666/76ef9d84-0b9e-11e5-8925-5996438afce4.PNG)

Pasul 2)
- Am introdus un rand nou in grid-ul "Cotatii furnizori pe proiect"  si l-am salvat cu butonul "Salveaza" din rand:

![t4](https://cloud.githubusercontent.com/assets/12709454/8006956/016aea20-0ba1-11e5-8fa8-35c6f8e1d122.PNG)

Pasul 3)
- Am mai intrat inca o data in proiectul nou creat ( referinta client 4656789 ) in fereastra "Proiecte -> Proiecte" cu ajutorul butonului "detalii":

![t5](https://cloud.githubusercontent.com/assets/12709454/8007022/61e46610-0ba1-11e5-8ba8-63335988b44d.PNG)

Pasul 4) 
- Am observat ca in grid-ul "Cotatii furnizori pe proiect" la randul nou creat s-au salvat alte detalii decat cele pe care le-am introdus eu:

![t6](https://cloud.githubusercontent.com/assets/12709454/8007049/9d1ceebe-0ba1-11e5-9c5c-168191724ff1.PNG)

**Comment by t1b1c** [comment]
problema asta are aceiasi cauza cu #18 
verifica daca s-a rezolvat
