### ISSUE TITLE
Export Cotatie in Excel produce o inregistrare goala

### ISSUE THREAD

**Issue by andreicorbu** [SoftulmeuRo/traduceri#2]
Pasul 1)
- Am intrat in fereastra "Proiecte -> Proiecte"
- Am intrat pe un proiect existent prin butonul "detalii"

![tr4](https://cloud.githubusercontent.com/assets/12709454/7959801/b1992b94-0a04-11e5-84f4-b10778129b56.PNG)

Pasul 2) 
- Am intrat pe un task existent prin comanda "detalii"

![tr5](https://cloud.githubusercontent.com/assets/12709454/7959838/fd38d090-0a04-11e5-9975-beeb0bf54914.PNG)

Pasul 3)
- In task-ul respectiv am completat forma "Cotatie pe task".
- Am efectuat un export prin butonul "Excel"

![tr3](https://cloud.githubusercontent.com/assets/12709454/7959904/4ae52faa-0a05-11e5-9405-37497fca8598.PNG)

Pasul 4) 
- Am intrat in fisierul excel creat si am observat ca nu imi aprare nici o inregistrare:

![tr6](https://cloud.githubusercontent.com/assets/12709454/7959963/a7c76b70-0a05-11e5-842a-fc46414acad3.PNG)

**Comment by t1b1c** [comment]
Nu este corecta observatia ca nu-ti apare nici o inregistrare!
Apare o inregistrare pt Document 1 dar fara valori

**Comment by t1b1c** [comment]
invalid si duplicat cu #3
