### ISSUE TITLE
Problema "Cotatii furnizori pe task" - Bug 1

### ISSUE THREAD

**Issue by andreicorbu** [SoftulmeuRo/traduceri#3]
Pasul 1)
- Am intrat in fereastra "Proiecte -> Proiecte"
- Am intrat pe un proiect existent prin butonul "detalii"

![tr4](https://cloud.githubusercontent.com/assets/12709454/7959801/b1992b94-0a04-11e5-84f4-b10778129b56.PNG)

Pasul 2) 
- Am intrat pe un task existent prin comanda "detalii"

![tr5](https://cloud.githubusercontent.com/assets/12709454/7959838/fd38d090-0a04-11e5-9975-beeb0bf54914.PNG)

Pasul 3) 
- Am completat formularul "Cotatii furnizori pe task":
- Am efectuat un export in excel:

![tr7](https://cloud.githubusercontent.com/assets/12709454/7960387/e35f5802-0a08-11e5-94f5-e095ef60d43d.PNG)

Pasul 4)

- Am deschis fisierul excel creat si am cosntata ca nu s-a incarcat nici o intrare.

![tr8](https://cloud.githubusercontent.com/assets/12709454/7960396/fb1e6514-0a08-11e5-90e5-9f8f594c7fd6.PNG)

**Comment by t1b1c** [comment]
duplicat la #2
