### ISSUE TITLE
Salvarea datelor in fereastra Cotatie task din ecranul "Adauga priect simplu" sterge campurile completate

### ISSUE THREAD

**Issue by LoredanaChitaru** [SoftulmeuRo/traduceri#4]
Pasul 1
       Am intrat in ecranul "Proiecte -> Proiecte" 
![proiecte](https://cloud.githubusercontent.com/assets/12709407/7960338/89f9df4e-0a08-11e5-8492-d815173603d1.jpg)

Pasul 2
       Am selectat "Adauga proiect simplu"
![adauga proiect simplu](https://cloud.githubusercontent.com/assets/12709407/7960351/ac636abe-0a08-11e5-994c-28148629413e.jpg)

Pasul 3
       Am completat toate campurile din sectiunea "Proiect si Task" si am dat "Salvare" dupa care am completat campurile din "Cotatie Task". Insa cand am dat salvare, toate datele introduse in  sectiunea cotatie task au disparut.

![cotaie pe task](https://cloud.githubusercontent.com/assets/12709407/7960433/36c60fe0-0a09-11e5-835d-f4e5ef1630ef.jpg)

**Comment by t1b1c** [comment]
duplicat cu #16
