### ISSUE TITLE
In gridul "Cotatie furnizor pe task" selectorul nu este afisat corect

### ISSUE THREAD

**Issue by andreicorbu** [SoftulmeuRo/traduceri#5]
Pasul 1)
- Am intrat in fereastra "Proiecte -> Proiecte"
- Am creat un proiect simplu prin comanda "Adauga proiect simplu":

![tr9](https://cloud.githubusercontent.com/assets/12709454/7960470/7e530caa-0a09-11e5-9427-4c6e545ab1fe.PNG)

Pasul 2) 
- In proiectul nou creat am completat formularul "Cotatii furnizori pe task"

![tr14](https://cloud.githubusercontent.com/assets/12709454/7960669/e6ca2394-0a0a-11e5-8b9f-53fca7da8ed3.PNG)

Pasul 3)
- Am dat "save" pe randul nou creat:

![tr11](https://cloud.githubusercontent.com/assets/12709454/7960625/a63f66f4-0a0a-11e5-878f-6bf99234f4c2.PNG)

Pasul 4)

- Dupa ce am dat save am observat ca primul nume al traducatorului a fost transformat in selector insa cel de-al doilea nume ramane needitabil.

![tr12](https://cloud.githubusercontent.com/assets/12709454/7960726/58995c38-0a0b-11e5-9c7b-c8bc9c3ce0a3.PNG)

**Comment by t1b1c** [comment]
asa trebuie sa functioneze (FbD)
