### ISSUE TITLE
La selectorul "Selectare contact" din "Proiect simplu" nu apare campul pentru introducerea datelor 

### ISSUE THREAD

**Issue by andreicorbu** [SoftulmeuRo/traduceri#7]
Pasul 1)
- Am intrat in ecranul "Proiecte -> Proiecte"
- Am introdus un proiect simplu din butonul "Adauga proiect simplu"

![tr](https://cloud.githubusercontent.com/assets/12709454/7979382/50dbd196-0aa7-11e5-8d00-8f007d075046.PNG)

Pasul 2)
- Am introdus un Client din selectorul "Selectare client"
- Am incercat sa introduc un contact din selectorul "Selectare contact"

![tr2](https://cloud.githubusercontent.com/assets/12709454/7979390/6407e7f0-0aa7-11e5-830f-8f7a2f7db955.PNG)

Pasul 3)
- Cand s-a deschis selectorul am observat ca lipseste campul de cautare desi am un buton de "Search", iar datele sunt incarcate automat:

![tr3](https://cloud.githubusercontent.com/assets/12709454/7979457/010102bc-0aa8-11e5-8010-5d29b2fc2629.PNG)

**Comment by t1b1c** [comment]
duplicat cu #9
