### ISSUE TITLE
In ecranul "Pregatire Facturare", in feresasta pentru "selectare contact" nu apare casuta pentru selectarea datelor

### ISSUE THREAD

**Issue by LoredanaChitaru** [SoftulmeuRo/traduceri#9]
1. Am intrat in ecranul "Pregatire Facturare" din tabul "Facturare".
![pregatire facturare](https://cloud.githubusercontent.com/assets/12709407/7980086/485795e0-0aad-11e5-8a56-7f845af2b7f4.jpg)

2. Am selectat un sablon si un client 
![selectare](https://cloud.githubusercontent.com/assets/12709407/7980127/9b60b258-0aad-11e5-9d93-b3d16044d102.jpg)

3. Cand am dat sa selectez si persoana de contact, am observat ca fereasta deschisa nu are casuta pentru cautare desi exista butonul de search, iar persoana de contact este incarcata automat.
![pers contact](https://cloud.githubusercontent.com/assets/12709407/7980179/142247d8-0aae-11e5-8137-60cbb51ed459.jpg)

Desi a raportat si andrei aceasta problema, el a raportat-o pentru alt ecran, si am cnsiderat ca este necesar sa o raportez si pentru ecranul acesta.

**Comment by t1b1c** [comment]
asa trebuie sa functioneze (FBD)
